<?php $AllPartnerApp=array (
  100 => 
  array (
    1 => 
    array (
      'PartnerId' => '1',
      'mixed_sign' => '',
      'name' => '狸猫',
      'AppId' => '100',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '1',
      'game_site' => 'www.lmgame.com',
      'comment' => '{"notes":""}',
      'AreaId' => '1',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
  ),
  101 => 
  array (
    1 => 
    array (
      'PartnerId' => '1',
      'mixed_sign' => '',
      'name' => '狸猫',
      'AppId' => '101',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '1',
      'game_site' => '',
      'comment' => '{"notes":""}',
      'AreaId' => '1',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
    2 => 
    array (
      'PartnerId' => '2',
      'mixed_sign' => '',
      'name' => '韩国运营商1',
      'AppId' => '101',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '1',
      'game_site' => '',
      'comment' => '{"notes":""}',
      'AreaId' => '2',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
    3 => 
    array (
      'PartnerId' => '3',
      'mixed_sign' => '',
      'name' => '美国运营商1',
      'AppId' => '101',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '1',
      'game_site' => '',
      'comment' => '{"notes":""}',
      'AreaId' => '3',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
    4 => 
    array (
      'PartnerId' => '4',
      'mixed_sign' => '',
      'name' => '台湾运营商21',
      'AppId' => '101',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '2',
      'game_site' => '',
      'comment' => '{"notes":""}',
      'AreaId' => '4',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
    5 => 
    array (
      'PartnerId' => '5',
      'mixed_sign' => '',
      'name' => '台湾合作商2',
      'AppId' => '101',
      'LoginStart' => '0',
      'NextStart' => '0',
      'NextEnd' => '0',
      'PayStart' => '0',
      'PayEnd' => '0',
      'income_type' => '1',
      'income_rate' => '2',
      'game_site' => '',
      'comment' => '{"notes":""}',
      'AreaId' => '1',
      'coin_rate' => '1.0000',
      'IsActive' => '0',
    ),
  ),
); return $AllPartnerApp;?>