<?php $AllApp=array (
  100 => 
  array (
    'AppId' => '100',
    'app_sign' => 'homepage',
    'name' => '公司官网rrrr',
    'pic' => '',
    'app_pic' => '',
    'ClassId' => '4',
    'AppLevelRule' => '0',
    'app_desc' => '',
    'site_url' => '',
    'exchange_rate' => '1',
    'data_url' => '',
    'comment' => '{"coin_name":"\\u72f8\\u732b\\u5e01"}',
  ),
  101 => 
  array (
    'AppId' => '101',
    'app_sign' => 'infinite_h',
    'name' => '无尽英雄',
    'pic' => '',
    'app_pic' => '',
    'ClassId' => '5',
    'AppLevelRule' => '0',
    'app_desc' => '',
    'site_url' => '',
    'exchange_rate' => '100',
    'data_url' => '',
    'comment' => '{"coin_name":"\\u91d1\\u5238"}',
  ),
  102 => 
  array (
    'AppId' => '102',
    'app_sign' => 'test1',
    'name' => '测试游戏1',
    'pic' => '',
    'app_pic' => '',
    'ClassId' => '5',
    'AppLevelRule' => '0',
    'app_desc' => '',
    'site_url' => '',
    'exchange_rate' => '1000',
    'data_url' => '',
    'comment' => '{"coin_name":"\\u94f6\\u5e01"}',
  ),
  103 => 
  array (
    'AppId' => '103',
    'app_sign' => 'test2',
    'name' => '测试游戏2',
    'pic' => '',
    'app_pic' => '',
    'ClassId' => '5',
    'AppLevelRule' => '0',
    'app_desc' => '',
    'site_url' => '',
    'exchange_rate' => '10000',
    'data_url' => '',
    'comment' => '{"coin_name":"\\u94dc\\u5e01"}',
  ),
); return $AllApp;?>